# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44d6a08fb5ac341d0f69b6eb210323a4"
name = "quote-app"
handle = "quote-app-11"
application_url = "https://red-rfc-vienna-rotary.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "yousifs-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://red-rfc-vienna-rotary.trycloudflare.com/auth/callback",
  "https://red-rfc-vienna-rotary.trycloudflare.com/auth/shopify/callback",
  "https://red-rfc-vienna-rotary.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
